-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Avion"
(
    "idAvion" bigint NOT NULL,
    "Modelo" text COLLATE pg_catalog."default" NOT NULL,
    "Peso" double precision NOT NULL,
    "Capacidad" bigint NOT NULL,
    "idHangar" bigint NOT NULL,
    "idPiloto" bigint NOT NULL,
    CONSTRAINT "Avion_pkey" PRIMARY KEY ("idAvion")
);

CREATE TABLE IF NOT EXISTS public."Hangar"
(
    "idHangar" bigint NOT NULL,
    "Capacidad" bigint NOT NULL,
    "Localizacion" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Hangar_pkey" PRIMARY KEY ("idHangar")
);

CREATE TABLE IF NOT EXISTS public."Piloto"
(
    "Nro_Licencia" bigint NOT NULL,
    "Restricciones" text COLLATE pg_catalog."default" NOT NULL,
    "Salario" double precision NOT NULL,
    "Turno" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Piloto_pkey" PRIMARY KEY ("Nro_Licencia")
);

ALTER TABLE IF EXISTS public."Avion"
    ADD CONSTRAINT "idHangar" FOREIGN KEY ("idHangar")
    REFERENCES public."Hangar" ("idHangar") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Avion"
    ADD CONSTRAINT "idPiloto" FOREIGN KEY ("idPiloto")
    REFERENCES public."Piloto" ("Nro_Licencia") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;